Schwarz/Models/LicaoAprendida.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Schwarz.Models
{
    public class LicaoAprendida
    {

        [Key]
        public int IDLicaoAprendida { get; set; }

        [Required(ErrorMessage = "O campo Fonte é obrigatório!")]
        public string Fonte { get; set; } = "Schwarz";
        
        [Required(ErrorMessage = "O campo Planejado é obrigatório!")]
        public string Planejado { get; set; }

        [Required(ErrorMessage = "O campo Realizado é obrigatório!")]
        public string Realizado { get; set; }

        [Required(ErrorMessage = "O campo Motivo é obrigatório!")]
        public string Motivo { get; set; }

        [Display(Name = "Funcionário")]
        [ForeignKey("Funcionario")]
        public int IDFuncionario { get; set; }
        public virtual Funcionario? Funcionario { get; set; }

        [Display(Name = "Cliente")]
        [ForeignKey("Cliente")]
        public int? IDCliente{ get; set; }
        public virtual Cliente? Cliente { get; set; }

        public DateTime Data { get; set; } = DateTime.Now;

        public string? Processo { get; set; }

        [Display(Name = "Nome da Peça")]
        public string? NomePeca { get; set; }

        [Display(Name = "Código Interno")]
        public string? CodigoInterno { get; set; }

        [Display(Name = "Lição Aprendida")]
        [Required(ErrorMessage = "A Lição Aprendida é obrigatória!")]
        public string Descricao { get; set; }

        [Display(Name = "Positivo/Negativo")]
        public bool Positivo { get; set; }

        public virtual ICollection<LicaoAprendidaAnexo>? LicaoAprendidaAnexos { get; set; }

        [NotMapped]
        public List<IFormFile>? Arquivos { get; set; }
    }
}

Schwarz/Controllers/LicaoAprendidaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Schwarz.Data;
using Schwarz.Models;

namespace Schwarz.Controllers
{
    [Authorize(Roles = "LicaoAprendida, Admin")]
    public class LicaoAprendidaController : Controller
    {
        private readonly SchwarzContext _context;

        public LicaoAprendidaController(SchwarzContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<LicaoAprendida> schwarzContext = (from l in _context.LicaoAprendida select new LicaoAprendida
            {
                IDLicaoAprendida = l.IDLicaoAprendida,
                Cliente = new Cliente { Nome = l.Cliente.Nome },
                Fonte = l.Fonte,
                Data = l.Data,
                Processo = l.Processo,
                CodigoInterno = l.CodigoInterno,
                NomePeca = l.NomePeca,
                Planejado = l.Planejado,
                Realizado = l.Realizado,
                Motivo = l.Motivo,
                Descricao = l.Descricao,
                Positivo = l.Positivo,
                LicaoAprendidaAnexos = l.LicaoAprendidaAnexos,
                Funcionario = new Funcionario { Nome = l.Funcionario.Nome }
            }).ToList();
            return View(schwarzContext);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var licaoAprendida = await _context.LicaoAprendida
                .FirstOrDefaultAsync(m => m.IDLicaoAprendida == id);
            if (licaoAprendida == null)
            {
                return NotFound();
            }

            return View(licaoAprendida);
        }

        public IActionResult Create()
        {
            ViewData["Clientes"] = new SelectList(_context.Cliente, "IDCliente", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LicaoAprendida licaoAprendida)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    licaoAprendida.Data = DateTime.Now;
                    using var transaction = _context.Database.BeginTransaction();

                    _context.Add(licaoAprendida);
                    await _context.SaveChangesAsync();

                    if (licaoAprendida.Arquivos != null && licaoAprendida.Arquivos.Count > 0)
                    {
                        foreach (var file in licaoAprendida.Arquivos)
                        {
                            if (file.Length > 0)
                            {
                                using (var memoryStream = new MemoryStream())
                                {
                                    file.CopyTo(memoryStream);
                                    byte[] fileBytes = memoryStream.ToArray();

                                    string tipoMime = file.ContentType;
                                    string fileName = file.FileName;

                                    LicaoAprendidaAnexo anexo = new(licaoAprendida.IDLicaoAprendida, fileName, fileBytes, tipoMime);
                                    _context.Add(anexo);
                                    _context.SaveChanges();
                                }
                            }
                        }
                    }
                    transaction.Commit();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["MensagemErro"] = "Houve um erro, por favor tente novamente, detalhe do erro:" + ex.Message;
                    return RedirectToAction("Create");
                }
            }
            return View(licaoAprendida);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var licaoAprendida = await _context.LicaoAprendida.FindAsync(id);
            if (licaoAprendida == null)
            {
                return NotFound();
            }
            ViewData["Clientes"] = new SelectList(_context.Cliente, "IDCliente", "Nome");
            return View(licaoAprendida);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, LicaoAprendida licaoAprendida)
        {
            if (id != licaoAprendida.IDLicaoAprendida)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(licaoAprendida);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LicaoAprendidaExists(licaoAprendida.IDLicaoAprendida))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(licaoAprendida);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var licaoAprendida = await _context.LicaoAprendida.FindAsync(id);
            if (licaoAprendida == null)
            {
                return NotFound();
            }
            if (licaoAprendida.LicaoAprendidaAnexos != null)
            {
                foreach (var licaoAprendidaArquivo in licaoAprendida.LicaoAprendidaAnexos)
                {
                    _context.Remove(licaoAprendidaArquivo);
                }
            }

            _context.LicaoAprendida.Remove(licaoAprendida);
            await _context.SaveChangesAsync();
            return Ok();
        }

        private bool LicaoAprendidaExists(int id)
        {
            return _context.LicaoAprendida.Any(e => e.IDLicaoAprendida == id);
        }

        [HttpPost]
        public IActionResult AdicionarAnexo(IFormFileCollection files, int idLicaoAprendida)
        {
            try
            {
                foreach (var file in files)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        file.CopyTo(memoryStream);
                        byte[] fileBytes = memoryStream.ToArray();

                        string tipoMime = file.ContentType;
                        string fileName = file.FileName;

                        LicaoAprendidaAnexo licaoAprendidaAnexo= new(idLicaoAprendida, fileName, fileBytes, tipoMime);
                        _context.Add(licaoAprendidaAnexo);
                        _context.SaveChanges();
                    }
                }
                return Ok();
            }

            catch (Exception ex)
            {
                return Json(new
                {
                    error = "Ocorreu um erro ao adicionar o anexo: " + ex.Message
                });
            }
        }

        [HttpPost]
        public IActionResult RemoverAnexo(int id)
        {
            var anexo = _context.LicaoAprendidaAnexo.Find(id);
            if (anexo != null)
            {
                _context.LicaoAprendidaAnexo.Remove(anexo);
                _context.SaveChanges();
                return Ok();
            }
            return NotFound();
        }

    }
}

Schwarz/Views/LicaoAprendida/Index.cshtml
@model IEnumerable<Schwarz.Models.LicaoAprendida>

@{
    ViewData["Title"] = "Lições";
    Layout = "_Layout";
}
<div class="my-2 flex sm:flex-row flex-col">
    <a asp-action="Create" asp-controller="LicaoAprendida" class="group block max-w-xs ml-auto rounded-lg p-6 bg-white ring-1 ring-slate-900/5 shadow-lg space-y-3 hover:bg-red-600 hover:ring-red-800">
        <div class="flex items-center space-x-3">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 group-hover:text-white">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 18v-5.25m0 0a6.01 6.01 0 001.5-.189m-1.5.189a6.01 6.01 0 01-1.5-.189m3.75 7.478a12.06 12.06 0 01-4.5 0m3.75 2.383a14.406 14.406 0 01-3 0M14.25 18v-.192c0-.983.658-1.823 1.508-2.316a7.5 7.5 0 10-7.517 0c.85.493 1.509 1.333 1.509 2.316V18" />
            </svg>

            <h3 class="text-slate-900 group-hover:text-white text-sm font-semibold">Cadastrar Lição</h3>
        </div>
    </a>
</div>

<div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto my-4">
    <div class="bg-white inline-block min-w-full shadow rounded-lg overflow-hidden p-5">
        <table id="table">
            <thead>
                <tr>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.IDFuncionario)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.IDCliente)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.Fonte)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.Data)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.Processo)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.CodigoInterno)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.NomePeca)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.Planejado)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.Realizado)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.Motivo)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.Descricao)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        @Html.DisplayNameFor(model => model.Positivo)
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        Arquivos
                    </th>
                    <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                        Ações
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    var cor = item.Positivo ? "text-green-600" : "text-red-600";

                    <tr class="@cor">
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.Funcionario.Nome)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.Cliente.Nome)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.Fonte)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.Data)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.Processo)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.CodigoInterno)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.NomePeca)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.Planejado)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.Realizado)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.Motivo)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @Html.DisplayFor(modelItem => item.Descricao)
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @if (item.Positivo)
                            {
                                <text>Positivo</text>
                            }
                            else
                            {
                                <text>Negativo</text>
                            }
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            @if (item.LicaoAprendidaAnexos != null)
                            {
                                foreach (var arquivo in item.LicaoAprendidaAnexos)
                                {
                                    <a href="data:@arquivo.TipoMIME;base64,@Convert.ToBase64String(arquivo.Conteudo)" download="@arquivo.Nome" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">@arquivo.Nome</a>
                                }
                            }
                            else
                            {
                                <text>Sem Arquivos</text>
                            }
                        </td>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                            <a class="text-black rounded-lg mt-2 p-2 bg-white ring-2 ring-amber-800 shadow-lg space-y-3 hover:bg-amber-500 hover:text-white inline-block" asp-action="Edit" asp-route-id="@item.IDLicaoAprendida">Editar</a>
                            <button class="text-black rounded-lg mt-2 p-2 bg-white ring-2 ring-red-800 shadow-lg space-y-3 hover:bg-red-600 hover:text-white inline-block btn-delete" data-licao-id="@item.IDLicaoAprendida">Deletar</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    $(document).ready(function () {
        $.fn.dataTable.moment('DD/MM/YYYY');

        var table = $('#table').DataTable({
            "order": [],
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.13.4/i18n/pt-BR.json"
            },
            "dom": 'lBfrtip',
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            "scrollY": "60vh",
            "scrollCollapse": true,
            "autoWidth": true,
            "responsive": true,
            "paging": true,
            "buttons": [
                {
                    extend: 'excelHtml5',
                    text: '<i class="fa fa-file-excel"></i> Excel',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5, 6, 7, 8,9]
                    }
                },
                {
                    extend: 'print',
                    text: '<i class="fa fa-print"></i> Imprimir',
                    className: 'btn btn-primary',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5, 6, 7, 8,9]
                    }
                },
                {
                    extend: 'pdfHtml5',
                    text: '<i class="fa fa-file-pdf"></i> PDF',
                    className: 'btn btn-danger',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5, 6, 7, 8,9]
                    }
                }
            ]
        });

        table.on('init.dt', function () {
            HideLoading();
        });

        $('.btn-delete').click(function () {
            if (confirm('Tem certeza que deseja deletar a lição?')) {
                var licaoId = $(this).data('licao-id');
                console.log(licaoId);
                $.ajax({
                    url: '/LicaoAprendida/Delete',
                    method: 'POST',
                    data: { id: licaoId },
                    success: function (data) {
                        var row = table.row($('button[data-licao-id="' + licaoId + '"]').closest('tr'));
                        row.remove().draw();
                        alert('Lição deletada com sucesso!')
                    },
                    error: function (error) {
                        alert('Erro ao deletar a licão: ' + error.responseText);
                    }
                });
            }
        });
    });

</script>