Schwarz/Models/PareQualidade.cs
using Schwarz.Data;
using Schwarz.Statics;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Schwarz.Models
{
	public class PareQualidade
	{
		[Key]
		public int IDPareQualidade { get; set; }

		[ForeignKey("Funcionario")]
		[Display(Name = "Funcionário")]
		[Required(ErrorMessage = "Selecione o Funcionário!")]
		public int IDFuncionario { get; set; }
		public virtual Funcionario? Funcionario { get; set; }

		[Display(Name = "Descrição")]
		public string Descricao { get; set; }

		[Required(ErrorMessage = "A Data é obrigatória!")]
		public DateTime Data { get; set; } = DateTime.Now;

		[Required(ErrorMessage = "Selecione o Setor onde ocorreu!")]
		public string Setor { get; set; }

		[Required(ErrorMessage = "O Código é obrigatório!")]
		[Display(Name = "Código do Item")]
		[MinLength(9, ErrorMessage = "O código deve ter no mínimo 9 digítos!")]
		[MaxLength(9, ErrorMessage = "O código deve ter no máximo 9 digítos!")]
		public string CodigoItem { get; set; }

		[Required(ErrorMessage = "A Quantidade é obrigatória!")]
		[Display(Name = "Quantidade Bloqueada")]
		public int QuantidadeBloqueada { get; set; }

		[Display(Name = "Status")]
		public string Status { get; set; } = StatusPare.EmAnalise;

		[Display(Name = "Observações do Líder")]
		public string? ObservacoesLider { get; set; }

		[Display(Name = "Observações da Qualidade")]
		public string? ObservacoesQualidade { get; set; }

		[Display(Name = "Pontuação")]
		public int? Pontuacao { get; set; }
		public bool PontuacaoValida { get; set; } = true;

		[NotMapped]
		public string DataFormatada => Data.ToString("dd/MM/yyyy");
	}
}

Schwarz/Controllers/Api/PareQualidadeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Schwarz.Data;
using Schwarz.Models;
using Schwarz.Statics;

namespace Schwarz.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize(Roles = $"{Roles.PareQualidade}, {Roles.Lider}, {Roles.Admin}")]
    public class PareQualidadeController : ControllerBase
    {
        private readonly SchwarzContext _context;
        public PareQualidadeController(SchwarzContext schwarzContext)
        {
            _context = schwarzContext;
        }

        [Authorize(Roles = $"{Roles.PareQualidade}, {Roles.Admin}")]
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteQualidade(int id)
        {
            var pareQualidade = await _context.PareQualidade.FindAsync(id);
            if (pareQualidade != null)
            {
                _context.PareQualidade.Remove(pareQualidade);
                _context.SaveChanges();
                return Ok();
            }

            return NotFound();
        }

        [HttpPut("AprovacaoLider")]
        public async Task<IActionResult> AprovacaoLider([FromForm] int id, [FromForm] string? observacoes = null)
        {
            var pareQualidade = await _context.PareQualidade.FindAsync(id);
            if (pareQualidade == null)
            {
                return NotFound();
            }
            pareQualidade.Status = StatusPare.AprovadoLider;
            pareQualidade.ObservacoesLider = observacoes;
            _context.PareQualidade.Update(pareQualidade);
            _context.SaveChanges();

            return Ok();
        }

        [HttpPut("ReprovacaoLider")]
        public async Task<IActionResult> ReprovacaoLider([FromForm] int id, [FromForm] string? observacoes = null)
        {
            var pareQualidade = await _context.PareQualidade.FindAsync(id);
            if (pareQualidade == null)
            {
                return NotFound();
            }
            pareQualidade.Status = StatusPare.ReprovadoLider;
            pareQualidade.ObservacoesLider = observacoes;
            _context.PareQualidade.Update(pareQualidade);
            _context.SaveChanges();

            return Ok();
        }

        [Authorize(Roles = $"{Roles.PareQualidade}, {Roles.Admin}")]
        [HttpPut("AprovacaoQualidade")]
        public async Task<IActionResult> AprovacaoQualidade([FromForm] int id, [FromForm] string? observacoes = null, [FromForm] int? pontuacao = null)
        {
            var pareQualidade = await _context.PareQualidade.FindAsync(id);
            if (pareQualidade == null)
            {
                return NotFound();
            }
            pareQualidade.Status = StatusPare.AprovadoQualidade;
            pareQualidade.ObservacoesQualidade = observacoes;
            pareQualidade.Pontuacao = pontuacao;
            _context.PareQualidade.Update(pareQualidade);
            _context.SaveChanges();

            return Ok();
        }

        [Authorize(Roles = $"{Roles.PareQualidade}, {Roles.Admin}")]
        [HttpPut("ReprovacaoQualidade")]
        public async Task<IActionResult> ReprovacaoQualidade([FromForm] int id, [FromForm] string? observacoes = null, [FromForm] int? pontuacao = null)
        {
            var pareQualidade = await _context.PareQualidade.FindAsync(id);
            if (pareQualidade == null)
            {
                return NotFound();
            }
            pareQualidade.Status = StatusPare.ReprovadoQualidade;
            pareQualidade.ObservacoesQualidade = observacoes;
            pareQualidade.Pontuacao = pontuacao;
            _context.PareQualidade.Update(pareQualidade);
            _context.SaveChanges();

            return Ok();
        }


    }
}

Schwarz/Controllers/PareQualidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Castle.Core.Smtp;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Schwarz.Data;
using Schwarz.Models;
using Schwarz.Services.Interfaces;
using Schwarz.Statics;

namespace Schwarz.Controllers
{
    public class PareQualidadeController : Controller
    {
        private readonly SchwarzContext _context;
        private readonly IEmailService _emailService;

        public PareQualidadeController(SchwarzContext context, IEmailService emailService)
        {
            _context = context;
            _emailService = emailService;
        }

        public async Task<IActionResult> Index()
        {
            var model = _context.PareQualidade;
            return View(await model.ToListAsync());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PareQualidade pareQualidade)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pareQualidade);
                await _context.SaveChangesAsync();
                string subject = "PARE de Qualidade do Produto Cadastrado";
                string nomeFuncionario = _context.Funcionario.Find(pareQualidade.IDFuncionario).Nome;
                string emailMessage = $"PARE de Qualidade cadastrada por: {nomeFuncionario} <br/> Descrição: {pareQualidade.Descricao} <br/>" + "Link do site:  <a href =\"http://192.168.2.96:5242/PareQualidade\">Sistema Integrado</a>";

                _emailService.SendEmail(subject, emailMessage, "rtavares@schwarz.com.br");
                _emailService.SendEmail(subject, emailMessage, "thiago.iaczkowski@schwarz.com.br");
                _emailService.SendEmail(subject, emailMessage, "jose@schwarz.com.br");

                if (pareQualidade.Funcionario.FuncionarioLider.Email != null)
                {
                    _emailService.SendEmail(subject, emailMessage, pareQualidade.Funcionario.FuncionarioLider.Email);
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Create", "Pare");
        }

        [HttpGet]
        [Authorize(Roles = $"{Roles.PareQualidade}, {Roles.Admin}")]
        public async Task<IActionResult> Edit(int id)
        {
            var pareQualidade = await _context.PareQualidade.FindAsync(id);
            if (pareQualidade == null)
            {
                return NotFound();
            }
            ViewData["Falhas"] = new SelectList(_context.Falha, "CodigoEDescricao", "CodigoEDescricao");
            ViewData["Setores"] = new SelectList(_context.Funcionario.Where(x => x.Ativo).Select(x => new { x.Setor }).Distinct(), "Setor", "Setor");
            ViewData["Funcionarios"] = new SelectList(_context.Funcionario.Where(x => x.Ativo).Select(x => new { x.IDFuncionario, x.Nome }), "IDFuncionario", "Nome");
            return View(pareQualidade);
        }

        [HttpPost]
        [Authorize(Roles = $"{Roles.PareQualidade}, {Roles.Admin}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PareQualidade pareQualidade)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.PareQualidade.Update(pareQualidade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;

                }
                return RedirectToAction("Index");
            }
            ViewData["Setores"] = new SelectList(_context.Funcionario.Where(x => x.Ativo).Select(x => new { x.Setor }).Distinct(), "Setor", "Setor");
            ViewData["Funcionarios"] = new SelectList(_context.Funcionario.Where(x => x.Ativo).Select(x => new { x.IDFuncionario, x.Nome }), "IDFuncionario", "Nome");
            return View(pareQualidade);
        }
    }
}

Schwarz/Views/PareQualidade/Edit.cshtml
@using Schwarz.Statics
@model PareQualidade
@{
    ViewData["Title"] = "Editar";
    Layout = "_Layout";
}

<div class="container mx-auto">
    <div class="flex justify-center px-6 my-12">
        <div class="border border-1 border-red-500 w-full lg:w-7/12 bg-white p-2 rounded-lg">
            <h3 class="pt-4 text-2xl text-center">Formulário de Edição</h3>
            <form id="form" method="post" class="px-8">
                <div class="mb-4">
                    <label asp-for="IDFuncionario" class="block mb-2 text-sm font-bold"></label>
                    <select asp-for="IDFuncionario" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline select2" asp-items="ViewBag.Funcionarios">
                    </select>
                    @Html.ValidationMessageFor(x => x.IDFuncionario)
                </div>
                <div class="mb-4">
                    <label asp-for="Descricao" class="block mb-2 text-sm font-bold"></label>
                    <input asp-for="Descricao" class="w-full px-3 py-2 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"></input>
                </div>
                <div class="mb-4">
                    <label asp-for="Data" class="block mb-2 text-sm font-bold"></label>
                    <input asp-for="Data" class="w-full px-3 py-2 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"></input>
                    @Html.ValidationMessageFor(x => x.Data)
                </div>

                <div class="mb-4">
                    <label asp-for="Setor" class="block mb-2 text-sm font-bold"></label>
                    <select asp-for="Setor" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" asp-items="ViewBag.Setores">
                    </select>
                    @Html.ValidationMessageFor(x => x.Setor)
                </div>
                <div class="mb-4">
                    <label asp-for="CodigoItem" class="block mb-2 text-sm font-bold"></label>
                    <input asp-for="CodigoItem" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" />
                    @Html.ValidationMessageFor(x => x.CodigoItem)
                </div>
                <div class="mb-4">
                    <label asp-for="QuantidadeBloqueada" class="block mb-2 text-sm font-bold"></label>
                    <input asp-for="QuantidadeBloqueada" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" />
                    @Html.ValidationMessageFor(x => x.QuantidadeBloqueada)
                </div>
                <div class="mb-4">
                    <label asp-for="Status" class="block mb-2 text-sm font-bold"></label>
                    <select asp-for="Status" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline">
                        @foreach (var status in StatusPare.QualidadeStatus)
                        {
                            <option value="@status">@status</option>
                        }
                    </select>
                    @Html.ValidationMessageFor(x => x.Status)
                </div>
                <div class="mb-4">
                    <label asp-for="ObservacoesLider" class="block mb-2 text-sm font-bold"></label>
                    <textarea asp-for="ObservacoesLider" style="min-height: calc(1em + 0.75rem + 100px);" class=" placeholder="Observações do Líder"></textarea>
                </div>
                <div class="mb-4">
                    <label asp-for="ObservacoesQualidade" class="block mb-2 text-sm font-bold"></label>
                    <textarea asp-for="ObservacoesQualidade" style="min-height: calc(1em + 0.75rem + 100px);" class=" placeholder="Observações da Qualidade"></textarea>
                    @Html.ValidationMessageFor(x => x.ObservacoesQualidade)
                </div>
                <div class="mb-4">
                    <label asp-for="Pontuacao" class="block mb-2 text-sm font-bold"></label>
                    <input asp-for="Pontuacao" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" placeholder="Digite a pontuação" />
                    @Html.ValidationMessageFor(x => x.Pontuacao)
                </div>
                <div class="my-6">
                    <input type="hidden" asp-for="IDPareQualidade" />
                    <input type="submit" value="Editar" class="w-full px-4 py-4 font-bold text-white bg-gradient-to-r from-red-300 to-red-500 rounded-full hover:bg-gradient-to-r hover:from-red-500 hover:to-red-300 rounded-full hover:cursor-pointer focus:outline-none focus:shadow-outline" />
                </div>
            </form>
        </div>
    </div>
</div>

Schwarz/Views/PareQualidade/_PartialCreate.cshtml
@using Microsoft.AspNetCore.Identity
@using Schwarz.Areas.Identity.Data
@using Schwarz.Services.Interfaces
@using Schwarz.Statics

@inject SignInManager<SchwarzUser> SignInManager
@inject IUserService UserService
@model PareQualidade

<form asp-action="Create" asp-controller="PareQualidade" method="post" id="formQualidade" class="hidden">
    <div>
        <div class="mb-3">
            <label asp-for="IDFuncionario" class="block mb-2 text-sm font-bold"></label>
            <select asp-for="IDFuncionario" id="funcionarioQualidade" class="select2" asp-items="ViewBag.Funcionarios">
                @if (SignInManager.IsSignedIn(User))
                {
                    <option selected value="@UserService.GetUser(User).Funcionario.IDFuncionario">@UserService.GetUser(User).Funcionario.Nome</option>
                }
                else
                {
                    <option selected disabled value="">Selecione o funcionário</option>
                }
            </select>
            @Html.ValidationMessageFor(x => x.IDFuncionario)
        </div>
        @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.PareQualidade))
        {
            <div class="mb-3">
                <label asp-for="Data" class="block mb-2 text-sm font-bold"></label>
                <input type="datetime-local" asp-for="Data" value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss")" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" autocomplete="off" onchange="this.setAttribute('value', this.value);" />
                @Html.ValidationMessageFor(x => x.Data)
            </div>
        }
        <div class="mb-3">
            <label asp-for="Setor" class="block mb-2 text-sm font-bold"></label>
            <select asp-for="Setor" class="select2" asp-items="ViewBag.Setores">
                @if (SignInManager.IsSignedIn(User))
                {
                    <option selected value="@UserService.GetUser(User).Funcionario.Setor">@UserService.GetUser(User).Funcionario.Setor</option>
                }
                else
                {
                    <option selected disabled value="">Selecione o Setor</option>
                }
            </select>
            @Html.ValidationMessageFor(x => x.Setor)
        </div>

        <div class="mb-3">
            <label asp-for="CodigoItem" class="block mb-2 text-sm font-bold"></label>
            <input asp-for="CodigoItem" type="number" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" autocomplete="off" placeholder="Código do item" maxlength="9" />
            @Html.ValidationMessageFor(x => x.CodigoItem)
        </div>
        <div class="mb-3">
            <label asp-for="QuantidadeBloqueada" class="block mb-2 text-sm font-bold"></label>
            <input asp-for="QuantidadeBloqueada" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" autocomplete="off" placeholder="Quantidade de Peças Bloqueadas" />
            @Html.ValidationMessageFor(x => x.QuantidadeBloqueada)
        </div>
        <div class="mb-3">
            <label asp-for="Descricao" class="block mb-2 text-sm font-bold"></label>
            <select asp-for="Descricao" class="select2" asp-items="ViewBag.Falhas">
                <option selected value="">Selecione a Falha</option>
            </select>
        </div>
        <div class="mb-3">
            <label asp-for="Descricao" class="block mb-2 text-sm font-bold"></label>
            <textarea asp-for="Descricao" class="w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" autocomplete="off" placeholder="Descreva a Falha"></textarea>
        </div>
    </div>
    <div class="mb-3">
        <input type="submit" value="Cadastrar" class="w-full px-4 py-4 font-bold text-white bg-gradient-to-r from-red-300 to-red-500 rounded-full hover:bg-gradient-to-r hover:from-red-500 hover:to-red-300 hover:cursor-pointer focus:outline-none focus:shadow-outline" />
    </div>
</form>